name: MAVEN
on:
  workflow_dispatch:

   
jobs:

  Clone:
    runs-on: [ self-hosted ]
    steps:
    
      - name: Print the workspace
        run: echo ${{ github.workspace }}
        
      - name: Clear workspace
        run: rm -rf ${{ github.workspace }}/*
      
      - name: Checkout code
        run: |
            git clone https://github.com/NishanthOrganization/simple-java-maven-app.git
            pwd

  Build:
    runs-on: [ self-hosted ]
    needs: Clone
    steps:
      - name: Run tests
        run: echo "Running tests..."

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: "Nish-1992,username2"
      
      - name: build
        if: ${{ steps.manual_approval.outputs.approved == 'true' }}
        run: |
            echo ${{ github.workspace }}
            cd simple-java-maven-app
            mvn clean install
